<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Company>Kannu Contributors</Company>
    <Product>Kannu for Windows</Product>
    <Copyright>Copyright (C) 2026 Kannu Contributors. GPL-3.0-or-later.</Copyright>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
